Entity/UserSubscription.php
<?php

/**
 * @author Rafał Muszyński <rafal.muszynski@sourcefabric.org>
 * @copyright 2014 Sourcefabric o.p.s.
 * @license http://www.gnu.org/licenses/gpl-3.0.txt
 */
namespace Newscoop\PaywallBundle\Entity;

use Newscoop\Entity\Publication;
use Newscoop\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Newscoop\PaywallBundle\Discount\DiscountableInterface;

/**
 * Subscription entity.
 *
 * @ORM\Entity(repositoryClass="Newscoop\PaywallBundle\Entity\Repository\UserSubscriptionRepository")
 * @ORM\Table(name="plugin_paywall_user_subscriptions")
 */
class UserSubscription implements DiscountableInterface, ProlongableItemInterface, PriceableInterface
{
    const TYPE_PAID = 'P';
    const TYPE_PAID_NOW = 'PN';
    const TYPE_TRIAL = 'T';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", name="Id")
     *
     * @var int
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Newscoop\Entity\User")
     * @ORM\JoinColumn(name="IdUser", referencedColumnName="Id")
     *
     * @var Newscoop\Entity\User
     */
    protected $user;

    /**
     * @ORM\ManyToOne(targetEntity="Newscoop\PaywallBundle\Entity\Subscription")
     * @ORM\JoinColumn(name="IdSubscription", referencedColumnName="id")
     *
     * @var Newscoop\PaywallBundle\Entity\Subscriptions
     */
    protected $subscription;

    /**
     * @ORM\ManyToOne(targetEntity="Order", inversedBy="items")
     * @ORM\JoinColumn(name="order_id", referencedColumnName="id", nullable=false)
     *
     * @var Order
     */
    protected $order;

    /**
     * @ORM\Column(type="integer", name="discount_total")
     *
     * @var int
     */
    protected $discountTotal = 0;

    /**
     * @ORM\ManyToOne(targetEntity="Newscoop\Entity\Publication")
     * @ORM\JoinColumn(name="IdPublication", referencedColumnName="Id")
     *
     * @var Newscoop\Entity\Publication
     */
    protected $publication;

    /**
     * @ORM\Column(type="decimal", name="ToPay")
     *
     * @var float
     */
    protected $toPay = 0.0;

    /**
     * @ORM\Column(name="Type")
     *
     * @var string
     */
    protected $type;

    /**
     * @ORM\Column(name="Currency")
     *
     * @var string
     */
    protected $currency;

    /**
     * @ORM\ManyToOne(targetEntity="Newscoop\PaywallBundle\Entity\Trial")
     * @ORM\JoinColumn(name="trial_id", referencedColumnName="id")
     *
     * @var Newscoop\PaywallBundle\Entity\Trial
     */
    protected $trial;

    /**
     * Subscription status visible for admin.
     *
     * @ORM\Column(name="Active")
     *
     * @var string
     */
    protected $active;

    /**
     * @ORM\Column(type="datetime", name="created_at")
     *
     * @var DateTime
     */
    protected $created_at;

    /**
     * @ORM\Column(type="datetime", name="expire_at", nullable=true)
     *
     * @var DateTime
     */
    protected $expire_at;

    /**
     * Custom field.
     *
     * @ORM\Column(type="boolean", name="custom")
     *
     * @var bool
     */
    protected $custom;

    /**
     * Second custom field.
     *
     * @ORM\Column(type="boolean", name="custom_2")
     *
     * @var bool
     */
    protected $customOther;

    /**
     * To hide from users totally.
     *
     * @ORM\Column(type="boolean", name="is_active")
     *
     * @var bool
     */
    protected $is_active;

    /**
     * Is prolonged?
     *
     * @ORM\Column(type="boolean", name="prolonged")
     *
     * @var bool
     */
    protected $prolonged = false;

    /**
     * @ORM\Column(type="datetime", name="notify_sent_first", nullable=true)
     *
     * @var \DateTime
     */
    protected $notifySentLevelOne;

    /**
     * @ORM\Column(type="datetime", name="notify_sent_second", nullable=true)
     *
     * @var \DateTime
     */
    protected $notifySentLevelTwo;

    /**
     * @ORM\Column(type="datetime", name="updated_at", nullable=true)
     *
     * @var \DateTime
     */
    protected $updated;

    /**
     * @ORM\Column(type="array", name="duration")
     *
     * @var array
     */
    protected $duration;

    protected $discount;

    /**
     * @ORM\OneToMany(targetEntity="Modification", mappedBy="orderItem", orphanRemoval=true, cascade={"all"})
     *
     * @var ArrayCollection
     */
    protected $modifications;

    /**
     * @ORM\ManyToMany(targetEntity="Discount", cascade={"persist"})
     * @ORM\JoinTable(name="plugin_paywall_order_item_discount",
     *      joinColumns={
     *          @ORM\JoinColumn(name="order_item_id", referencedColumnName="Id")
     *      },
     *      inverseJoinColumns={
     *          @ORM\JoinColumn(name="discount_id", referencedColumnName="id")
     *      }
     *  )
     *
     * @var Discount
     */
    protected $discounts;

    /**
     * @ORM\ManyToOne(targetEntity="UserSubscription", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="Id", onDelete="SET NULL")
     *
     * @var UserSubscription
     */
    protected $parent;

    /**
     * @ORM\OneToMany(targetEntity="UserSubscription", mappedBy="parent")
     * @ORM\OrderBy({"created_at" = "DESC"})
     */
    protected $children;

    /**
     * @ORM\Column(type="datetime", name="starts_at", nullable=true)
     *
     * @var DateTime
     */
    protected $startsAt;

    public function __construct()
    {
        $this->currency = '';
        $this->active = 'N';
        $this->created_at = new \DateTime();
        $this->is_active = false;
        $this->custom = false;
        $this->customOther = false;
        $this->type = self::TYPE_PAID;
        $this->notifySentLevelOne = null;
        $this->notifySentLevelTwo = null;
        $this->modifications = new ArrayCollection();
        $this->discounts = new ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return (int) $this->id;
    }

    /**
     * Set subscription.
     *
     * @param Newscoop\PaywallBundle\Entity\Subscription $subscription
     */
    public function setSubscription($subscription)
    {
        $this->subscription = $subscription;

        return $this;
    }

    /**
     * Get subscription.
     *
     * @return Newscoop\PaywallBundle\Entity\Subscription_specification
     */
    public function getSubscription()
    {
        return $this->subscription;
    }

    /**
     * Set user.
     *
     * @param Newscoop\Entity\User $user
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user.
     *
     * @return Newscoop\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set publication.
     *
     * @param Newscoop\Entity\Publication $publication
     *
     * @return Newscoop\Entity\Subscription
     */
    public function setPublication(Publication $publication)
    {
        $this->publication = $publication;

        return $this;
    }

    /**
     * Get publication.
     *
     * @return Newscoop\Entity\Publication
     */
    public function getPublication()
    {
        return $this->publication;
    }

    /**
     * Get publication name.
     *
     * @return string
     */
    public function getPublicationName()
    {
        return $this->publication->getName();
    }

    /**
     * Get publication id.
     *
     * @return int
     */
    public function getPublicationId()
    {
        return $this->publication->getId();
    }

    /**
     * Set to pay.
     *
     * @param float $toPay
     *
     * @return Newscoop\Entity\Subscription
     */
    public function setToPay($toPay)
    {
        $this->toPay = (float) $toPay;

        return $this;
    }

    /**
     * Get to pay.
     *
     * @return float
     */
    public function getToPay()
    {
        return (float) $this->toPay;
    }

    /**
     * Set to pay.
     *
     * @param float $toPay
     *
     * @return Newscoop\Entity\Subscription
     */
    public function setPrice($toPay)
    {
        $this->toPay = (float) $toPay;

        return $this;
    }

    /**
     * Get to pay.
     *
     * @return float
     */
    public function getPrice()
    {
        return (float) $this->toPay;
    }

    /**
     * Set type.
     *
     * @param string $type
     *
     * @return Newscoop\Entity\Subscription
     */
    public function setType($type)
    {
        $this->type = strtoupper($type) === self::TYPE_TRIAL ? self::TYPE_TRIAL : self::TYPE_PAID;

        return $this;
    }

    /**
     * Get type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Test if is trial.
     *
     * @return bool
     */
    public function isTrial()
    {
        return $this->type === self::TYPE_TRIAL;
    }

    /**
     * Set active.
     *
     * @param bool $active
     *
     * @return Newscoop\Entity\Subscription
     */
    public function setActive($active)
    {
        $this->active = 'N';
        if ($active) {
            $this->active = 'Y';
        }

        return $this;
    }

    /**
     * Is active.
     *
     * @return bool
     */
    public function isActive()
    {
        return strtoupper($this->active) === 'Y';
    }

    /**
     * Get currency.
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Set currency.
     *
     * @return string
     */
    public function setCurrency($currency)
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Get trial.
     *
     * @return Trial
     */
    public function getTrial()
    {
        return $this->trial;
    }

    /**
     * Set trial.
     *
     * @return Trial
     */
    public function setTrial($trial)
    {
        $this->trial = $trial;

        return $this;
    }

    /**

Resources/views/Admin/admin.html.twig
{% extends 'NewscoopNewscoopBundle::admin_layout.html.twig' %}

{% block admin_title %}{{ parent() }} - {{ 'paywall.title'|trans }}{% endblock %}
{% block admin_page_title_content %}{{ 'paywall.toolbar.label.configuration'|trans }}{% endblock %}

{% block admin_stylesheets %}
<link rel="stylesheet" type="text/css" href="{{ asset('/js/select2/select2.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('public/bundles/newscooppaywall/css/admin_paywall.css') }}" />
{% endblock %}

{% block admin_scripts %}
<script src="{{ asset('/js/select2/select2.js') }}"></script>
<script src="{{ asset('public/bundles/newscooppaywall/js/paywall.js') }}"></script>
{% endblock %}

{% block admin_content %}
<div class="plugin-container">
	{% include "NewscoopPaywallBundle::admin_menu.html.twig" with {active: 1} %}
	{% if hasPermission('plugin_paywall_subscription-add') or hasPermission('plugin_paywall_subscriptions-manage') %}
	<div id="add-subscription" style="padding: 10px 10px 30px 10px;">
		<form id="confForm" action="{{ path('newscoop_paywall_admin_update', {'id': subscription_id }) }}" method="post" {{ form_enctype(form) }} >
			<table id="step1" border="0" cellspacing="0" cellpadding="0" class="box_table">
				<tbody>
					<tr>
						<td colspan="2" align="left">
							<input style="min-width: 240px" class="save-button" name="step1" value="{{ 'paywall.btn.button1'|trans }} (1)" disabled>
							<input style="min-width: 240px" class="button" name="step3" value="{{ 'paywall.label.defineduration'|trans }} (2)" disabled>
							<input style="min-width: 240px" class="button" name="step2" value="{{ 'paywall.btn.button2'|trans }} (3)" disabled><br><br>
							<div class="alert alert-info"><span class="glyphicon glyphicon-info-sign"></span> {{ 'paywall.step1.header'|trans }}</div>
						</td>
					</tr>
					<tr>
						<td>
							<div class="alert error"></div>
						</td>
					</tr>
					<tr>
						<td align="left">
							{{ form_label(form.name) }}
						</td>
					</tr>
					<tr>
						<td align="left" valign="top">
							{{ form_widget(form.name, {'attr' : {'class' : 'form-control'}}) }}
						</td>
					</tr>
					<tr>
						<td align="left">
							{{ form_label(form.type) }}
						</td>
					</tr>
					<tr>
						<td>
							{{ form_widget(form.type, {'attr' : {'class' : 'form-control'}}) }}
						</td>
					</tr>
					<tr>
						<td align="left">
							{{ form_label(form.price) }}
						</td>
					</tr>
					<tr>
						<td align="left" valign="top">
							{{ form_widget(form.price, {'attr' : {'class' : 'form-control'}}) }}
						</td>
					</tr>
					<tr>
						<td align="left">
							<label>{{ 'paywall.step1.form.label.currency'|trans }}</label>
						</td>
					</tr>
					<tr>
						<td align="left" valign="top">
							{% if defaultCurrency %}
							<span class="label label-info">{{defaultCurrency}}</span>
							{% else %}
							<span class="alert alert-danger">No default currency selected. Please, define one in Currencies tab.</span>
							{% endif %}
						</td>
					</tr>
					<tr>
						<td align="left">
							{{ form_label(form.isTemplate) }}
						</td>
					</tr>
					<tr>
						<td align="left" valign="top">
							{{ form_widget(form.isTemplate) }}
						</td>
					</tr>
					<tr>
						<td align="left">
							{{ form_label(form.description) }} ({{ 'paywall.step1.form.label.optional'|trans }})
						</td>
					</tr>
					<tr>
						<td align="left" valign="top">
							{{ form_widget(form.description, {'attr' : {'class' : 'form-control'}}) }}
						</td>
					</tr>
					<tr>
						<td colspan="2"><hr></td>
					</tr>
					<tr>
						<td colspan="2" align="right" style="padding-top: 10px;">
							<input type="submit" id="next" value="{{ 'paywall.btn.next'|trans }}" class="btn btn-primary">
						</td>
					</tr>
					{{ form_rest(form) }}
				</tbody>
			</table>
		</form>
		<form id="step2Form" action="{{ path('newscoop_paywall_admin_step2', {'id': subscription_id }) }}" method="post" {{ form_enctype(formSpecification) }}>
			<table id="step2" border="0" cellspacing="0" cellpadding="0" class="box_table">
				<tbody>
					<tr>
						<td colspan="2" align="left">
							<input class="button" style="min-width: 240px" type="submit" name="step1" value="{{ 'paywall.btn.button1'|trans }} (1)" disabled>
							<input class="button" style="min-width: 240px" name="step3" value="{{ 'paywall.label.defineduration'|trans }} (2)" disabled>
							<input class="save-button" style="min-width: 240px" name="step2" value="{{ 'paywall.btn.button2'|trans }} (3)" disabled><br><br>
							<div style="float: left"><strong>{{ 'paywall.step2.header'|trans }}</strong><br><br>

								<table border="0" cellspacing="0" cellpadding="0" class="display">
									<tbody>
										<tr>
											<td>
												<div class="alert error"></div>
											</td>
										</tr>
										<tr>
											<td align="left">
												{{ 'paywall.step2.label.publication'|trans }}:
											</td>
										</tr>
										<tr>
											<td align="left" valign="top">
												<input id="subscriptionName" name="subscriptionTitle" type="hidden"></input>
											</td>
										</tr>
										<tr>
											<td align="left" valign="top">
												<div id="selectPublications" style="width:350px" class="populate placeholder"></div>
												{{ form_widget(formSpecification.publication, {'attr' : {'style' : 'display: none'}}) }}
											</td>
										</tr>
										<tr>
											<td id="title-issue" align="left"></td>
										</tr>
										<tr>
											<td align="left" valign="top">
												<div id="selectIssues" style="width:350px" class="populate placeholder"></div>
												{{ form_widget(formSpecification.issue, {'attr' : {'style' : 'display: none'}}) }}
											</td>
										</tr>
										<tr>
											<td id="title-section" align="left"></td>
										</tr>
										<tr>
											<td align="left" valign="top">
												<div id="selectSections" style="width:350px" class="populate placeholder"></div>
												{{ form_widget(formSpecification.section, {'attr' : {'style' : 'display: none'}}) }}
											</td>
										</tr>
										<tr>
											<td id="title-article" align="left">
												{{ 'paywall.step2.label.article'|trans }}:
											</td>
										</tr>
										<tr>
											<td align="left" valign="top">
												<div id="selectArticles" name="articleNumber" style="width:350px" class="populate placeholder"></div>
												{{ form_widget(formSpecification.article, {'attr' : {'style' : 'display: none'}}) }}
											</td>
										</tr>
										{{ form_widget(formSpecification._token) }}
									</tbody>
								</table>
							</div>
							<div style="float: right">
								<table border="0" cellspacing="1" cellpadding="3" class="table_list">
									<tbody><tr class="table_list_header">
										<td align="left" id="titleBox" valign="top"></td>
										<td align="center" valign="top"></td>
										<tr>
											<td align="left">{{ 'paywall.step2.label.type'|trans }}:</td>
											<td id="typeBox"></td>
										</tr>
										<tr>
											<td align="left">{{ 'paywall.step2.label.price'|trans }}:</td>
											<td id="valueBox"></td>
										</tr>
										<tr>
											<td align="left">{{ 'paywall.step2.label.currency'|trans }}:</td>
											<td id="currencyBox">{% if defaultCurrency %}
											<span class="label label-info">{{defaultCurrency}}</span>
											{% else %}
											-
											{% endif %}</td>
										</tr>
									</tbody></table>
								</div>
							</div>
						</td>
					</tr>
					<tr>
						<tr>
							<td colspan="2"><hr></td>
						</tr>
						<td colspan="2" align="right" style="padding-top: 10px;">
							<input type="button" id="skip" value="{{ 'paywall.btn.skip'|trans }}" class="btn btn-default">
							<input type="submit" id="save" value="{{ 'paywall.btn.save'|trans }}" class="btn btn-primary">
						</td>
					</tr>
				</tbody>
			</table>
		</form>
		<form id="step3Form" class="form-inline" novalidate action="{{ path('newscoop_paywall_admin_update', {'id': subscription_id }) }}" method="post" {{ form_enctype(formSpecification) }}>
			<table id="step3" border="0" cellspacing="0" cellpadding="0" class="box_table">
				<tbody>
					<tr>
						<td colspan="2" align="left">
							<input class="button" type="submit" style="min-width: 240px" name="step1" value="{{ 'paywall.btn.button1'|trans }} (1)" disabled>
							<input class="save-button" style="min-width: 240px" name="step3" value="{{ 'paywall.label.defineduration'|trans }} (2)" disabled>
							<input class="button" style="min-width: 240px" name="step2" value="{{ 'paywall.btn.button2'|trans }} (3)" disabled>
							<div style="margin-top: 20px" class="alert alert-info"><span class="glyphicon glyphicon-info-sign"></span> {{ 'paywall.label.defineduration'|trans }}</div>
								<div class="form-group">
									<label>{{ 'paywall.step2.label.durationbox'|trans }}</label>
									{{ form_widget(formDuration.value) }}
									{{ form_widget(formDuration.attribute) }}
									{{ form_widget(formDuration.discount) }}
									<button style="margin-left: 20px;" type="submit" class="btn btn-xs btn-success">
										<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> {{ 'paywall.btn.add'|trans }}
									</button>

								{{ form_widget(formDuration._token) }}
								<br>
								<br>
								<table id="duration-table" class="table">
									<thead>
										<tr>
											<th>{{ 'paywall.step2.label.durationbox'|trans }}</th>
											<th>{{ 'paywall.label.discount'|trans }}</th>
											<th>{{ 'paywall.manage.label.options'|trans }}</th>
										</tr>
									</thead>
									<tbody>
										{% for range in ranges %}
										<tr id="{{ range.id }}">
											<td>{{ range.value }}{% if range.attribute == 'month' %} {{ 'paywall.label.months'|trans }} {% endif %}{% if range.attribute == 'day' %} {{ 'paywall.label.days'|trans }} {% endif %}</td>
											<td>{% if range.discount %} {{ range.discount.name}} ({{ range.discount.value * 100 }}%){% else %} - {% endif %}</td>
											<td><button type="button" id="remove-duration" data-path="{{ path('newscoop_paywall_admin_duration_remove', {'id': range.id }) }}" class="btn btn-xs btn-danger">
												<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> {{ 'paywall.btn.delete'|trans }}
											</button></td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
						</td>
					</tr>
					<tr>
						<tr>
							<td colspan="2"><hr></td>
						</tr>
						<td colspan="2" align="right" style="padding-top: 10px;">
							<input type="button" id="next-last" value="{{ 'paywall.btn.next'|trans }}" class="btn btn-primary">
						</td>
					</tr>
				</tbody>
			</table>
		</form>
	</div>
	{% else %}
		<div class="alert alert-danger" style="font-size: 14px"><center>{{ 'paywall.permissions.alert.add'|trans }}</center></div>
	{% endif %}
</div>
<script>
	$('form#step3Form').live('submit', function () {
		var that = $(this);
		var data = that.serialize();
		data += "&subscriptionName=" + encodeURIComponent($('#subscriptionconf_name').val());
		callServer('ping', [], function(json) {
			$.ajax({
				type: 'POST',
				url: "{{ path('newscoop_paywall_admin_duration', {'id': subscription_id }) }}",
				data: data,
				statusCode: {
	               403: function (response) {
	                  flashMessage('{{ 'paywall.permissions.alert.flash'|trans }}', 'error');
	               }
	            }, success: function (data) {
					if (data.status) {
						flashMessage("{{ 'paywall.success.added'|trans }}");
						if (data.duration) {
							var discount = "-";

							if (Object.keys(data.duration.discount).length > 0) {
								discount = data.duration.discount.name+' ('+(data.duration.discount.value * 100)+'%)';
							}

							var durationAttribute = '{{ 'paywall.label.months'|trans }}';
							if (data.duration.attribute === 'day') {
								durationAttribute = '{{ 'paywall.label.days'|trans }}';
							}

							$('#duration-table tbody').append(
								'<tr id="'+data.duration.id+'">'+
									'<td>'+data.duration.value+
									' '+durationAttribute+'</td>'+
									'<td>'+discount+'</td>'+
									'<td><button type="button" id="remove-duration" data-path="{{ path('newscoop_paywall_admin_duration_remove') }}/'+data.duration.id+'" class="btn btn-xs btn-danger">'+
										'<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> '+
									'{{ 'paywall.btn.delete'|trans }}</button></td>'+
								'</tr>'
							);
						} else {
							flashMessage("{{ 'paywall.error.notadded'|trans }}");
						}
					} else {
						if (data.errors.hasOwnProperty('value')) {
							flashMessage(data.errors.value[0], "error");
						} else {
							flashMessage("{{ 'paywall.msg.exists'|trans }}", "error");
						}
					}
				},
				error: function (rq, status, error) {
					if (status == 0 || status == -1) {
						flashMessage('Error occured!', "error");
					}
				}
			});
		});

		return false;
	});
	$('#remove-duration').live('click', function () {
		var that = $(this);
		callServer('ping', [], function(json) {
			$.ajax({
				type: 'POST',
				url: that.data('path'),
				statusCode: {
	               403: function (response) {
	                  flashMessage('{{ 'paywall.permissions.alert.flash'|trans }}', 'error');
	               }
	            }, success: function (data) {
					if (data.status) {
						flashMessage('{{ 'paywall.success.removed'|trans }}');
						that.parent().parent().remove();
					} else {
						flashMessage(data.message, "error");
					}
				},
				error: function (rq, status, error) {
					if (status == 0 || status == -1) {
						flashMessage('Error occured!', "error");
					}
				}
			});
		});

		return false;
	});
</script>
{% endblock %}