Entity/Order.php
<?php

/**
 * @author Rafał Muszyński <rafal.muszynski@sourcefabric.org>
 * @copyright 2015 Sourcefabric z.ú.
 * @license http://www.gnu.org/licenses/gpl-3.0.txt
 */

namespace Newscoop\PaywallBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Newscoop\Entity\User;

/**
 * Order entity.
 *
 * @ORM\Entity(repositoryClass="Newscoop\PaywallBundle\Entity\Repository\OrderRepository")
 * @ORM\Table(name="plugin_paywall_order")
 */
class Order implements OrderInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", name="id")
     *
     * @var int
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="UserSubscription", mappedBy="order", orphanRemoval=true, cascade={"all"})
     *
     * @var Collection
     */
    protected $items;

    /**
     * @ORM\Column(type="string", name="currency", length=3)
     *
     * @var string
     */
    protected $currency;

    /**
     * @ORM\Column(type="integer", name="total")
     *
     * @var int
     */
    protected $total = 0;

    /**
     * @ORM\Column(type="integer", name="items_total")
     *
     * @var int
     */
    protected $itemsTotal = 0;

    /**
     * @ORM\Column(type="integer", name="discount_total")
     *
     * @var int
     */
    protected $discountTotal = 0;

    /**
     * @ORM\ManyToOne(targetEntity="Newscoop\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="Id")
     *
     * @var User
     */
    protected $user;

    /**
     * @ORM\OneToMany(targetEntity="Modification", mappedBy="order", orphanRemoval=true, cascade={"all"})
     *
     * @var Collection
     */
    protected $modifications;

    /**
     * @ORM\OneToMany(targetEntity="Payment", mappedBy="order", orphanRemoval=true, cascade={"all"})
     *
     * @var Collection
     */
    protected $payments;

    /**
     * @ORM\ManyToMany(targetEntity="Discount", cascade={"persist"})
     * @ORM\JoinTable(name="plugin_paywall_order_discount",
     *      joinColumns={
     *          @ORM\JoinColumn(name="order_id", referencedColumnName="id")
     *      },
     *      inverseJoinColumns={
     *          @ORM\JoinColumn(name="discount_id", referencedColumnName="id")
     *      }
     *  )
     *
     * @var Collection
     */
    protected $discounts;

    /**
     * @ORM\Column(type="string", name="payment_state")
     *
     * @var string
     */
    protected $paymentState = PaymentInterface::STATE_NEW;

    /**
     * @ORM\Column(type="datetime", name="updated_at", nullable=true)
     *
     * @var \DateTime
     */
    protected $updatedAt;

    /**
     * @ORM\Column(type="datetime", name="created_at")
     *
     * @var \DateTime
     */
    protected $createdAt;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->modifications = new ArrayCollection();
        $this->payments = new ArrayCollection();
        $this->discounts = new ArrayCollection();
        $this->createdAt = new \DateTime();
    }

    /**
     * {@inheritdoc}
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * {@inheritdoc}
     */
    public function setItems(Collection $items)
    {
        $this->items = $items;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function countItems()
    {
        return $this->items->count();
    }

    /**
     * {@inheritdoc}
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * {@inheritdoc}
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function addItem($item)
    {
        if ($this->hasItem($item)) {
            return $this;
        }

        $this->items->add($item);

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function removeItem($item)
    {
        if ($this->hasItem($item)) {
            $this->items->removeElement($item);
        }

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function hasItem($item)
    {
        return $this->items->contains($item);
    }

    /**
     * {@inheritdoc}
     */
    public function getToPay()
    {
        return $this->getTotal();
    }

    /**
     * {@inheritdoc}
     */
    public function setToPay($total)
    {
        $this->setTotal($total);

        return $this;
    }

    /**
     * Gets the value of total.
     *
     * @return int
     */
    public function getTotal()
    {
        return $this->total / 100;
    }

    /**
     * Sets the value of total.
     *
     * @param int $total the total
     *
     * @return self
     */
    public function setTotal($total)
    {
        $this->total = $total * 100;

        return $this;
    }

    /**
     * Gets the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets the value of id.
     *
     * @param int $id the id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets the value of updatedAt.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Sets the value of updatedAt.
     *
     * @param \DateTime $updatedAt the updated at
     *
     * @return self
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Gets the value of createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Sets the value of createdAt.
     *
     * @param \DateTime $createdAt the created at
     *
     * @return self
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Gets the value of currency.
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Sets the value of currency.
     *
     * @param string $currency the currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getDiscountTotal()
    {
        return $this->discountTotal / 100;
    }

    /**
     * {@inheritdoc}
     */
    public function setDiscountTotal($discountTotal)
    {
        $this->discountTotal = $discountTotal * 100;

        return $this;
    }

    public function addDiscount($discount)
    {
        if (!$this->hasDiscount($discount)) {
            $this->discounts->add($discount);
        }

        return $this;
    }

    public function hasDiscount($discount)
    {
        return $this->discounts->contains($discount);
    }

    public function removeDiscount($discount)
    {
        if ($this->hasDiscount($discount)) {
            $this->discounts->removeElement($discount);
        }

        return $this;
    }

    /**
     * Gets the discounts.
     *
     * @return Collection
     */
    public function getDiscounts()
    {
        return $this->discounts;
    }

    /**
     * Sets the discounts.
     *
     * @param Collection $discounts the discounts
     *
     * @return self
     */
    public function setDiscounts(Collection $discounts)
    {
        $this->discounts = $discounts;

        return $this;
    }

    /**
     * Calculates total order price including
     * all discounts.
     *
     * @return self
     */
    public function calculateTotal()
    {
        $this->calculateItemsTotal();
        $this->total = ($this->itemsTotal / 100 + $this->discountTotal / 100) * 100;
        if ($this->total < 0) {
            $this->total = 0;
        }

        return $this;
    }

    /**
     * Calculates all items discounts and unit prices.
     *
     * @return self
     */
    public function calculateItemsTotal()
    {
        $itemsTotal = 0;
        $this->discountTotal = 0;
        foreach ($this->items as $item) {
            $item->calculateToPay();
            $itemsTotal += $item->getToPay();

            $this->discountTotal -= $item->getDiscountTotal() * 100;
        }

        $this->itemsTotal = round($itemsTotal, 2) * 100;

        return $this;
    }

    /**
     * Gets the value of itemsTotal.
     *
     * @return int
     */
    public function getItemsTotal()
    {
        return $this->itemsTotal / 100;
    }

    /**
     * Sets the value of itemsTotal.
     *
     * @param int $itemsTotal the items total
     *
     * @return self
     */
    public function setItemsTotal($itemsTotal)
    {
        $this->itemsTotal = $itemsTotal * 100;

        return $this;
    }

    /**
     * Gets the payments.
     *
     * @return Payment
     */
    public function getPayments()
    {
        return $this->payments;
    }

    public function getPaymentState()
    {
        return $this->paymentState;
    }

    public function setPaymentState($paymentState)
    {
        $this->paymentState = $paymentState;
    }

    public function addPayment(PaymentInterface $payment)
    {
        if (!$this->hasPayment($payment)) {
            $this->payments->add($payment);
            $payment->setOrder($this);
            $this->setPaymentState($payment->getState());
        }
    }

    public function removePayment(PaymentInterface $payment)
    {
        if ($this->hasPayment($payment)) {
            $this->payments->removeElement($payment);
            $payment->setOrder(null);
        }
    }

    public function hasPayment(PaymentInterface $payment)
    {

Resources/views/UserOrder/createItem.html.twig
{% import 'NewscoopPaywallBundle:Macros:buttons.html.twig' as buttons %}
{% extends 'NewscoopNewscoopBundle::admin_layout.html.twig' %}
{% form_theme form 'NewscoopPaywallBundle::forms.html.twig' %}

{% block admin_title %}{{ parent() }} - {{ 'paywall.title'|trans }}{% endblock %}
{% block admin_page_title_content %}{{ 'paywall.btn.createorderitem'|trans }}{% endblock %}

{% block admin_stylesheets %}
<link rel="stylesheet" type="text/css" href="{{ asset('public/bundles/newscooppaywall/css/admin_paywall.css') }}" />
{% endblock %}

{% block admin_scripts %}
{% endblock %}
{% block admin_content %}
<div class="plugin-container">
  {% include "NewscoopPaywallBundle::admin_menu.html.twig" with {active: 3} %}
  {{ form_errors(form) }}

  <form action="{{ path('paywall_plugin_userorder_createitem', {id: orderId}) }}" method="post" class="form-horizontal" novalidate>
      <div class="row">
        <br>
        <div class="col-md-10">
          {{ form_row(form.subscription, {'attr': {'class': 'form-control'}}) }}
          {{ form_row(form.duration, {'attr': {'class': 'form-control'}}) }}
          {{ form_row(form.type, {'attr': {'class': 'form-control'}}) }}
          {{ form_row(form.active, {'attr': {'class': 'form-control'}}) }}
          {{ form_widget(form._token) }}
        </div>
      </div>
      <hr>
      <center>
      <div class="form-actions">
        <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i> {{ 'paywall.btn.create'|trans }}</button>
        <a href="{{ app.request.headers.get('referer') }}" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> {{ 'paywall.btn.cancel'|trans }}</a>
    </div>
    </center>
  </form>
</div>
<script>
var $subscriptions = $('#orderItemForm_subscription');
$subscriptions.change(function() {
  var $form = $(this).closest('form');
  var data = {};
  data[$subscriptions.attr('name')] = $subscriptions.val();
  $.ajax({
    url : "{{ path('paywall_plugin_userorder_periods', {id: orderId}) }}",
    type: $form.attr('method'),
    dataType: 'html',
    data : data,
    success: function(html) {
      $('#orderItemForm_duration').replaceWith(
        $(html).find('#orderItemForm_duration')
      );
    }
  });
});
</script>
{% endblock %}

Resources/views/UserOrder/edit.html.twig
{% import 'NewscoopPaywallBundle:Macros:buttons.html.twig' as buttons %}
{% extends 'NewscoopNewscoopBundle::admin_layout.html.twig' %}

{% block admin_title %}{{ parent() }} - {{ 'paywall.title'|trans }}{% endblock %}
{% block admin_page_title_content %}{{ 'paywall.toolbar.label.discounts'|trans }}{% endblock %}

{% block admin_stylesheets %}
<link rel="stylesheet" type="text/css" href="{{ asset('admin-style/table.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('public/bundles/newscooppaywall/css/admin_paywall.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('/js/select2/select2.css') }}" />
{% endblock %}

{% block admin_scripts %}
{% endblock %}
{% block admin_content %}
<div class="plugin-container">
  {% for flashMessage in app.session.flashbag.get('success') %}
  <div class="alert alert-success alert-dismissible font-fix" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">{{ 'aes.btn.close'|trans}}</span></button>
    <center>{{ flashMessage }}</center>
  </div>
  {% endfor %}
{% for flashMessage in app.session.flashbag.get('error') %}
<div class="alert alert-danger alert-dismissible font-fix" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">{{ 'aes.btn.close'|trans}}</span></button>
  <center>{{ flashMessage }}</center>
</div>
  {% endfor %}
  {% include "NewscoopPaywallBundle::admin_menu.html.twig" with {active: 3} %}
  <div id="configure-paywall" class="box_table">
  <div class="pull-right" style="display: inline-flex;">
            {{ buttons.show(path('paywall_plugin_userorder_show', {'id': order.id})) }}
            {{ buttons.create(path('paywall_plugin_userorder_createitem', {'id': order.id}), 'paywall.btn.createorderitem'|trans) }}
        </div>
<br>
<hr>
      <div class="table">
      {% if order.items|length > 0 %}
          <div id="users-subscriptions" style="padding: 10px 10px 30px 10px;">
        <table cellpadding="0" cellspacing="0" border="0" class="display" style="width: 100%" id="users-subscriptionsTable">
            <thead>
                <tr>
                    <th>{{ 'paywall.step1.form.select.type.publication'|trans }}</th>
                    <th>{{ 'paywall.step1.form.label.subscription'|trans }}</th>
                    <th>{{ 'paywall.label.unitprice'|trans }}</th>
                    <th>{{ 'paywall.label.period'|trans }}</th>
                    <th>{{ 'paywall.label.total'|trans }}</th>
                    <th>{{ 'paywall.manage.label.firstNotify'|trans }}</th>
                    <th>{{ 'paywall.manage.label.secondNotify'|trans }}</th>
                    <th>{{ 'paywall.manage.label.expiresAt'|trans }}</th>
                    <th>{{ 'paywall.step2.label.active'|trans }}</th>
                    <th>{{ 'paywall.manage.label.options'|trans }}</th>
                </tr>
            </thead>
            <tbody>
        </table>
    </div>
          {% else %}
            <center>No order items.</center>
            <hr>
            <div class="form-actions">
              <a href="{{ app.request.headers.get('referer') }}" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> {{ 'paywall.btn.back'|trans }}</a>
          </div>
          {% endif %}
        </div>

    </div>
  </div>
  <script src="{{ asset('/js/select2/select2.js') }}"></script>
<script type="text/javascript">
function format(item) { return item.name; };
function formatDiv(item) { return "<div class='select2-results'>" + item.name + "</div>"; }

$(document).ready(function(){
    var translations = {'btn.deactivate': 'Deactivate',
        'label.active': 'Active',
        'label.deactivated': 'Deactivated',
        'btn.activate': 'Activate',
        'label.addsubscription': 'Add user subscription'
    };
    var typeDetails = $('#typeDetails span');
    var durationDetails = $('#durationDetails span');
    var priceDetails = $('#priceDetails span');
    var currencyDetails = $('#currencyDetails span');
    $('#users-subscriptionsTable').css('font-size', '13px');

    var oTable = $('#users-subscriptionsTable').dataTable( {
        'oLanguage': {
            'oPaginate': {
                'sFirst': '{{ 'paywall.datatable.label.first'|trans }}',
                'sNext': '{{ 'paywall.datatable.label.next'|trans }}',
                'sPrevious': '{{ 'paywall.datatable.label.previous'|trans }}',
                'sLast': '{{ 'paywall.datatable.label.last'|trans }}',
            },
            'sZeroRecords': '{{ 'paywall.datatable.label.norecords'|trans }}',
            'sSearch': '',
            'sInfo': '{{ 'paywall.datatable.table.info'|trans }}',
            'sEmpty': '{{ 'paywall.datatable.table.noentries'|trans }}',
            'sInfoFiltered': '{{ 'paywall.datatable.table.filtering'|trans }}',
            'sLengthMenu': '{{ 'paywall.datatable.table.menu'|trans }}',
            'sInfoEmpty': '',
        },
        "bProcessing": true,
        "bAutoWidth": true,
        "bPaging": true,
        "sDom": 'RCf<"clear">rtilp',
        "bJQueryUI": true,
        "sPaginationType": "full_numbers",
        "bServerSide": true,
        "sAjaxSource": Routing.generate('newscoop_paywall_userssubscriptions_loadsubscriptions', {id: {{ order.id }}}),
        "aoColumnDefs": [
            { 'bSortable': false, 'aTargets': [ 8 ] }
        ],
        "aoColumns" : [
            { "mData": "publication" },
            { "mData": "subscription" },
            { "mData": "topay" },
            { "mData": "period" },
            { "mData": "total" },
            { "mData": "firstNotify" },
            { "mData": "secondNotify" },
            { "mData": "expiresAt" },
            { "mData": "active", "sClass": "status"},
            { "mData": null, "sWidth": "28%"},
        ],
        fnRowCallback: function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
                $('td:eq(0)', nRow).parent().attr('id', aData['id']);
                if (aData['active'])
                {
                    $('td:eq(8)', nRow).attr('id','active');
                    $('td:eq(8)', nRow).html("{{ 'paywall.manage.label.active'|trans }}");
                } else {
                    $('td:eq(8)', nRow).attr('id','deactivated');
                    $('td:eq(8)', nRow).html("{{ 'paywall.manage.label.deactivated'|trans }}");
                }
                if (aData['firstNotify']) {
                    $('td:eq(5)', nRow).html(aData['firstNotify']['date']);
                } else {
                    $('td:eq(5)', nRow).html('-');
                }

                if (aData['secondNotify']) {
                    $('td:eq(6)', nRow).html(aData['secondNotify']['date']);
                } else {
                    $('td:eq(6)', nRow).html('-');
                }

                if (aData['expiresAt']) {
                    $('td:eq(7)', nRow).html(aData['expiresAt']['date']);
                } else {
                    $('td:eq(7)', nRow).html('-');
                }

                $('td:eq(9)', nRow).empty();
                $('td:eq(9)', nRow).append("<a class='details-subscription btn btn-xs btn-default' href='"+Routing.generate('newscoop_paywall_userssubscriptions_editsubscription', {'id': aData['id']})+"'><span class=\"glyphicon glyphicon-edit\"></span> {{ 'paywall.btn.edit'|trans }}</a>");
                $('td:eq(9)', nRow).append("<a class='delete-action btn btn-xs btn-default' id="+aData['id']+" href='"+Routing.generate('newscoop_paywall_userssubscriptions_delete', {'id': aData['id']})+"'><span class=\"glyphicon glyphicon-trash\"></span> {{ 'paywall.btn.delete'|trans }}</a>");
                if (aData['active']) {
                    $('td:eq(9)', nRow).append(" <a class='change-status btn btn-xs btn-default' id="+aData['id']+" href="+Routing.generate('newscoop_paywall_userssubscriptions_deactivate', {'id': aData['id']})+"><span class=\"glyphicon glyphicon-remove-circle\"></span> {{ 'paywall.btn.deactivate'|trans }}</a>");
                } else {
                    $('td:eq(9)', nRow).append(" <a class='change-status btn btn-xs btn-default' id="+aData['id']+" href="+Routing.generate('newscoop_paywall_userssubscriptions_activate', {'id': aData['id']})+"><span class=\"glyphicon glyphicon-ok-circle\"></span> {{ 'paywall.btn.activate'|trans }}</a>");
                }
        },
    });

    function refreshTable(tableId, urlData)
    {
      $.getJSON(urlData, null, function( json )
      {
        table = $(tableId).dataTable();
        oSettings = table.fnSettings();

        table.fnClearTable(this);

        for (var i=0; i<json.aaData.length; i++)
        {
          table.oApi._fnAddData(oSettings, json.aaData[i]);
        }

        oSettings.aiDisplay = oSettings.aiDisplayMaster.slice();
        table.fnDraw();
      });
    }

    $('#users-subscriptionsTable').on('click', '.change-status', function(event){
        var id = $(this).attr('id');
        var obj = $("#"+id);
        event.preventDefault();
        $.ajax($(this).attr('href'), {
           type: "POST",
           statusCode: {
              403: function (response) {
                 flashMessage('{{ 'paywall.permissions.alert.flash'|trans }}', 'error');
              }
           }, success: function (data) {
                if (data.status) {
                    if (obj.find('td.status').attr('id') === 'deactivated') {
                        refreshTable('#users-subscriptionsTable', Routing.generate('newscoop_paywall_userssubscriptions_loadsubscriptions', {id: {{ order.id }}}));
                        flashMessage('{{ 'paywall.flash.message.subscription.activated'|trans }}');
                    } else {
                        refreshTable('#users-subscriptionsTable', Routing.generate('newscoop_paywall_userssubscriptions_loadsubscriptions', {id: {{ order.id }}}));
                        flashMessage('{{ 'paywall.flash.message.subscription.deactivated'|trans }}');
                    }
                } else {
                    flashMessage('{{ 'paywall.flash.message.error'|trans }}', 'error');
                }
           },
        });
    });

    $('#users-subscriptionsTable').on('click', '.delete-action', function(event){
        var id = $(this).attr('id');
        var obj = $("tr#"+id);
        event.preventDefault();
        $.ajax($(this).attr('href'), {
           type: "POST",
           statusCode: {
              403: function (response) {
                 flashMessage('{{ 'paywall.permissions.alert.flash'|trans }}', 'error');
              }
           }, success: function (data) {
                if (data.status) {
                    flashMessage('{{ 'paywall.flash.message.subscription.deleted'|trans }}');
                    obj.remove();
                } else {
                    flashMessage('{{ 'paywall.flash.message.error'|trans }}', 'error');
                }
           },
        });
    });

    $('.dataTables_filter label input').addClass('form-control input-sm');
    $('.dataTables_filter label input').attr('placeholder', '{{ 'paywall.search'|trans }}');
});
</script>
{% endblock %}

Resources/views/UserOrder/show.html.twig
{% import 'NewscoopPaywallBundle:Macros:buttons.html.twig' as buttons %}
{% extends 'NewscoopNewscoopBundle::admin_layout.html.twig' %}

{% block admin_title %}{{ parent() }} - {{ 'paywall.title'|trans }}{% endblock %}
{% block admin_page_title_content %}{{ 'paywall.toolbar.label.discounts'|trans }}{% endblock %}

{% block admin_stylesheets %}
<link rel="stylesheet" type="text/css" href="{{ asset('public/bundles/newscooppaywall/css/admin_paywall.css') }}" />
{% endblock %}

{% block admin_scripts %}
{% endblock %}
{% block admin_content %}
<div class="plugin-container">
  {% for flashMessage in app.session.flashbag.get('success') %}
  <div class="alert alert-success alert-dismissible font-fix" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">{{ 'aes.btn.close'|trans}}</span></button>
    <center>{{ flashMessage }}</center>
  </div>
  {% endfor %}
  {% include "NewscoopPaywallBundle::admin_menu.html.twig" with {active: 3} %}
  <div id="configure-paywall" class="box_table">
  <div class="pull-right">
            {{ buttons.edit(path('paywall_plugin_userorder_edit', {'id': order.id})) }}
        </div>
        <br>
        <hr>
    <center>
      <div class="table">
      {% if order.items|length > 0 %}
        <table class="table">
          <thead>
            <tr>
              <th>Subscription</th>
              <th>Ordered at</th>
              <th>{{ 'paywall.manage.label.firstNotify'|trans }}</th>
              <th>{{ 'paywall.manage.label.secondNotify'|trans }}</th>
              <th>{{ 'paywall.manage.label.expiresAt'|trans }}</th>
              <th>Prolonged?</th>
              <th>{{ 'paywall.step2.label.active'|trans }}</th>
              <th>Period</th>
              <th>Unit Price</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            {% for item in order.items %}
            <tr>
              <td style="width: 20%;"><b>{{ item.subscription.name }}</b><br>
                <small>{{ item.subscription.description }}</small></td>
                <td>{{ item.createdAt|date('Y-m-d H:i:s') }}</td>
                <td>{% if item.notifySentLevelOne %}{{ item.notifySentLevelOne|date('Y-m-d H:i:s') }}{% else %}-{% endif %}</td>
                <td>{% if item.notifySentLevelTwo %}{{ item.notifySentLevelTwo|date('Y-m-d H:i:s') }}{% else %}-{% endif %}</td>
                <td>{% if item.expireAt %}{{ item.expireAt|date('Y-m-d H:i:s') }}{% else %}-{% endif %}</td>
                <td>{% if item.prolonged %}
                    <span class="label label-success">{{ 'paywall.manage.label.yes'|trans }}</span>
                {% else %}
                    <span class="label label-warning">{{ 'paywall.manage.label.no'|trans }}</span>
                {% endif %}</td>
                <td>{% if item.active %}
                    <span class="label label-success">{{ 'paywall.manage.label.active'|trans }}</span>
                {% else %}
                    <span class="label label-warning">{{ 'paywall.manage.label.deactivated'|trans }}</span>
                {% endif %}</td>
                <td>{{ item.duration.value }} {% if item.duration.attribute == "month" %}month(s){% endif %}</td>
                <td>{{ item.toPay / item.duration.value }} {{ item.currency }}</td>
                <td>{{ item.toPay }} {{ item.currency }}</td>
              </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <td class="active text-right" colspan="10">
                  <strong>Items total</strong>:
                  <span class="amount">{{ order.itemsTotal }} {{order.currency}}</span>
                </td>
              </tr>
              <tr class="promotion-discount">
                <td colspan="4">
                </td>
                <td class="text-right" colspan="10">
                  <strong>Discount total</strong>:
                  <span class="amount">{{ order.discountTotal('discount') }} {{order.currency}}</span>
                </td>
              </tr>

              <tr>
                <td class="text-right active text-success lead" colspan="10">
                  <strong>Total</strong>:
                  <span class="amount">{{order.total}}{{order.currency}}</span>
                </td>
              </tr>
            </tfoot>
          </table>
          {% else %}
            <center><span class="alert alert-info">{{'paywall.datatable.label.norecords'|trans}}</span></center>
            <hr>
            <div class="form-actions">
              <a href="{{ app.request.headers.get('referer') }}" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> {{ 'paywall.btn.back'|trans }}</a>
          </div>
          {% endif %}
        </div>
      </center>
    </div>
  </div>
  {% endblock %}